// Package ingress generates Caddy reverse-proxy configuration and
// /etc/hosts files for container service discovery.
//
// Internal mode: all services behind a single localhost block with path-based
// routing (https://localhost/dash/*, https://localhost/media/*).
//
// LetsEncrypt mode: one block per hostname with real TLS certs.
package ingress

import (
	"bytes"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"quartermaster/pkg/types"
)

var (
	caddyfilePath = "/var/lib/quartermaster/caddy/Caddyfile"
	hostsFilePath = "/var/lib/quartermaster/caddy/hosts"
)

type ServiceEntry struct {
	Name       string
	IP         net.IP
	Ports      []types.Port
	Ingress    *types.IngressConfig
	AutheliaIP string
}

func GenerateAll(services []ServiceEntry, domain string, tlsMode string) error {
	if tlsMode == "" {
		tlsMode = "internal"
	}
	for i := range services {
		if services[i].AutheliaIP == "" {
			for _, s := range services {
				if s.AutheliaIP != "" {
					services[i].AutheliaIP = s.AutheliaIP
					break
				}
			}
		}
	}
	if err := generateCaddyfile(services, domain, tlsMode); err != nil {
		return fmt.Errorf("caddyfile: %w", err)
	}
	return generateHosts(services)
}

func generateCaddyfile(services []ServiceEntry, domain string, tlsMode string) error {
	dir := filepath.Dir(caddyfilePath)
	os.MkdirAll(dir, 0755)
	os.MkdirAll(filepath.Join(dir, "data"), 0755)
	os.MkdirAll("/var/lib/quartermaster/authelia", 0755)

	var buf strings.Builder
	buf.WriteString("# Auto-generated by Quartermaster — do not edit\n\n")

	authIP := ""
	for _, s := range services {
		if s.AutheliaIP != "" {
			authIP = s.AutheliaIP
			break
		}
	}

	hasIngress := false

	if tlsMode == "letsencrypt" {
		// Production: one block per hostname.
		for _, s := range services {
			if s.Ingress == nil || s.IP == nil {
				continue
			}
			hasIngress = true
			host := s.Ingress.Host
			if domain != "" && !strings.Contains(host, ".") {
				host = host + "." + domain
			}
			buf.WriteString(fmt.Sprintf("%s {\n", host))
			// JSON access logging to stdout (captured by persistent logging).
			buf.WriteString("\tlog {\n\t\toutput stdout\n\t\tformat json\n\t}\n")
			buf.WriteString("\thandle /.well-known/* {\n\t\trespond 200\n\t}\n")
			buf.WriteString("\thandle /healthz {\n\t\trespond \"OK\" 200\n\t}\n")
			writeAuth(&buf, s, authIP)
			buf.WriteString(fmt.Sprintf("\thandle {\n\t\t\treverse_proxy %s:%d\n\t\t}\n", s.IP.String(), s.Ingress.Port))
			buf.WriteString("}\n\n")
		}
		// If authelia is running, add its own block.
		if authIP != "" && domain != "" {
			buf.WriteString(fmt.Sprintf("auth.%s {\n", domain))
			buf.WriteString("\tlog {\n\t\toutput stdout\n\t\tformat json\n\t}\n")
			buf.WriteString("\thandle /.well-known/* {\n\t\trespond 200\n\t}\n")
			buf.WriteString(fmt.Sprintf("\treverse_proxy %s:9091\n", authIP))
			buf.WriteString("}\n\n")
		}
	} else {
		// Internal mode: single localhost block with path-based routing.
		buf.WriteString("localhost {\n")
		buf.WriteString("    tls internal\n")
		for _, s := range services {
			if s.Ingress == nil || s.IP == nil {
				continue
			}
			hasIngress = true
			route := "/" + s.Ingress.Host + "/*"
			buf.WriteString(fmt.Sprintf("    handle_path %s {\n", route))
			writeAuth(&buf, s, authIP)
			buf.WriteString(fmt.Sprintf("        reverse_proxy %s:%d\n", s.IP.String(), s.Ingress.Port))
			buf.WriteString("    }\n")
		}
		buf.WriteString("}\n\n")
	}

	if !hasIngress {
		buf.WriteString(":80 {\n    respond \"Quartermaster Caddy — no ingress configured\"\n}\n")
	} else if tlsMode == "internal" {
		buf.WriteString(":80 {\n    respond <<EOF\n")
		buf.WriteString("Quartermaster Ingress (internal TLS)\n\n")
		for _, s := range services {
			if s.Ingress != nil && s.IP != nil {
				buf.WriteString(fmt.Sprintf("/%s/* → %s:%d\n", s.Ingress.Host, s.Ingress.Host, s.Ingress.Port))
			}
		}
		buf.WriteString("EOF\n")
		buf.WriteString("}\n")
	}

	return os.WriteFile(caddyfilePath, []byte(buf.String()), 0644)
}

func writeAuth(buf *strings.Builder, s ServiceEntry, authIP string) {
	if s.Ingress.Auth && authIP != "" {
		buf.WriteString(fmt.Sprintf("\tforward_auth %s:9091 {\n", authIP))
		buf.WriteString("\t\turi /api/authz/forward-auth\n")
		buf.WriteString("\t\tcopy_headers Authorization\n")
		buf.WriteString("\t}\n")
	}
}

func generateHosts(services []ServiceEntry) error {
	dir := filepath.Dir(hostsFilePath)
	os.MkdirAll(dir, 0755)
	os.MkdirAll(filepath.Join(dir, "data"), 0755)

	var buf strings.Builder
	buf.WriteString("# Auto-generated by Quartermaster\n")
	buf.WriteString("127.0.0.1 localhost\n")
	buf.WriteString("::1       localhost\n")

	for _, s := range services {
		if s.IP != nil {
			buf.WriteString(fmt.Sprintf("%-15s %s\n", s.IP.String(), s.Name))
		}
	}

	return os.WriteFile(hostsFilePath, []byte(buf.String()), 0644)
}

func ReloadCaddy() error {
	data, err := os.ReadFile(caddyfilePath)
	if err != nil {
		return fmt.Errorf("read caddyfile: %w", err)
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Post("http://localhost:2019/load", "text/caddyfile", bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("caddy admin API: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("caddy reload returned %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	return nil
}
